export type Lang = "en" | "sk";

type Publication = {
  id: string;
  pages: Number;
};

export const TRANSLATIONS = {
  sk: {
    sng: "Slovenská národná galéria",
    library: {
      "1": {
        title: "Bardejovské Kúpele v obrazoch",
        author: "Kornél Chyzer – Károly Divald",
        year: "1886",
        descriptions: [
          "Bardejovské Kúpele v obrazoch",
          "Pohľad na Bardejovské Kúpele od juhovýchodu",
          "Bardejovská ulica",
          "Kostolné námestie",
          "Hlavný prameň s kúpeľnou dvoranou",
          "Hlavná ulica",
          "Hlavná ulica",
          "Jazierko a Mestský hotel",
          "Kostolné námestie s novým kúpeľným domom",
          "Horúci prameň so starým kúpeľným domom",
          "„Sladký prameň“",
          "Sírový prameň",
          "Pamätník „Viera, láska a nádej“",
          "Sprcha",
          "Panská ulica",
          "Tanečná sála",
          "Pohľad na Bardejov od Kalvárie",
          "Bardejovská radnica a kostol",
          "Ruina hradu Zborov",
        ],
      },
      "2": {
        title: "Pamätný album",
        author: "Divaldov ateliér",
        year: "1890",
        descriptions: [
          "Pamätný album",
          "Pamätný album",
          "Titulný list pamätného albumu",
          "Károly Divald st.",
          "Imre Egey",
          "Skupinový portrét Károlya Divalda a jeho učňov a zamestnancov",
          "János Varga",
          "György Varga",
          "József Juhász",
          "Sándor Fekete Nagyiványi",
          "Károly Divald ml.",
          "Árpád Turzer",
          "Károly Mathea",
          "Joviek",
          "Lajos Divald",
          "Skupinový portrét zamestnancov svetlotlačiarne",
          "Gusztáv Matz",
          "Divaldove dcéry (zľava Borbála?, Emília?, Iren a Mária?)",
          "Alajos Klapok",
          "Lajos Farkas",
          "Emil Gertinger",
          "Béla Ajtai",
          "A. Brabez",
          "Gusztav Graeser",
          "Béla Zitkovszky",
          "Ödön (Edmund) Uher",
          "Adolf Divald",
          "József Ferenczy",
        ],
      },
      "3": {
        title:
          "Rimamuránsko Šalgótarjánska hutnícka akciová spoločnosť na Milenárnej výstave",
        author: "Károly Divald ml.",
        year: "1896",
      },
    },
  },
  en: {
    sng: "Slovak National Gallery",
    library: {
      "1": {
        title: "Bardejovské Kúpele in Pictures",
        author: "Kornél Chyzer – Károly Divald",
        year: "1886",
        descriptions: [
          "Bardejovské Kúpele in Pictures",
          '"View of Bardejovské Kúpele from the southeast"',
          "Bardejovská Street",
          "Church Square",
          "Main spring with spa hall",
          "Main Street",
          "Main Street",
          "Pond and City Hotel",
          '"Church Square with new spa house"',
          '"Hot spring with old spa house"',
          '"Sweet Spring"',
          "Sulphur spring",
          '"Faith, Love, and Hope" memorial',
          "Shower",
          "Panská Street",
          "Dance hall",
          "View of Bardejov from Calvary",
          "Bardejov town hall and church",
          "Ruins of Zborov Castle.",
        ],
      },
      "2": {
        title: "Commemorative Album",
        author: "Divald's Studio",
        year: "1890",
        descriptions: [
          "Commemorative Album",
          "Commemorative Album",
          "Commemorative Album title page",
          "Károly Divald Sr.",
          "Imre Egey",
          "Group portrait of Károly Divald and his apprentices and employees",
          "János Varga",
          "György Varga",
          "József Juhász",
          "Sándor Fekete Nagyiványi",
          "Károly Divald Jr.",
          "Árpád Turzer",
          "Károly Mathea",
          "Jovick",
          "Lajos Divald",
          "Group portrait of employees of the Collotype Printing House",
          "Gusztáv Matz",
          "Divald's daughters (from the left: Borbála?, Emilia?, Iren, and Maria?)",
          "Alajos Klapok",
          "Lajos Farkas",
          "Emil Gertinger",
          "Béla Ajtai",
          "A. Brabez",
          "Gusztav Graeser",
          "Béla Zitkovszky",
          "Ödön (Edmund) Uher",
          "Adolf Divald",
          "József Ferenczy",
        ],
      },
      "3": {
        title:
          "Rimamurány-Salgotarjan metallurgical joint-stock company at the Millennium Exhibition",
        author: "Károly Divald Jr",
        year: "1896",
      },
    },
  },
};

export const LIBRARY: Array<Publication> = [
  {
    id: "1",
    pages: 19,
  },
  {
    id: "2",
    pages: 29,
  },
  {
    id: "3",
    pages: 26,
  },
];
