export type Lang = "en" | "sk";

type Publication = {
  id: string;
  pages: Number;
};

export const TRANSLATIONS = {
  sk: {
    sng: "Slovenská národná galéria",
    library: {
      "1": {
        title: "Bardejovské Kúpele v obrazoch",
        author: "Kornél Chyzer – Károly Divald",
        year: "1886",
        photosTitles: [
          "Bardejovské Kúpele v obrazoch",
          "Pohľad na Bardejovské Kúpele od juhovýchodu",
          "Bardejovská ulica",
          "Kostolné námestie",
          "Hlavný prameň s kúpeľnou dvoranou",
          "Hlavná ulica",
          "Hlavná ulica",
          "Jazierko a Mestský hotel",
          "Kostolné námestie s novým kúpeľným domom",
          "Horúci prameň so starým kúpeľným domom",
          "Sladký prameň",
          "Sírový prameň",
          "Pamätník „Viera, láska a nádej“",
          "Sprcha",
          "Panská ulica",
          "Tanečná sála",
          "Pohľad na Bardejov od Kalvárie",
          "Bardejovská radnica a kostol",
          "Ruina hradu Zborov",
        ],
      },
      "2": {
        title: "Pamätný album",
        author: "Divaldov ateliér",
        year: "1890",
        photosDescriptions: [
          "",
          "",
          "Pri príležitosti 25. výročia založenia podniku Károlyho Divalda st. a jubilejnej 5000. snímky. 4. novembra 1890. Vaši zamestnanci",
          "",
          "November 1890 v Debrecíne. Učeník sa klania svojmu majstrovi a prináša plný prejav jeho úcty, keď má šťastie osláviť 60. narodeniny svojho života bohatého na zásluhy. Nech ho Boh Maďarov zachová v dobrom zdraví a veselej nálade na prospech a ochranu vlasti, rodiny a predkov dlhé, dlhé roky. Som a zostanem veriacim s mimoriadnou úctou. Imre Egey",
          "",
          "János Varga. Záhreb, 20. október 1890",
          "György Varga. Záhreb, 20. október 1890",
          "Juhász József †",
          "Najkrajšou odmenou, ktorú môže žiak dobrému učiteľovi dať, je ʼpocit vďačnostiʻ – ktorý cit preniká mojou dušou vždy, keď pomyslím na svoju životnú cestu. Sándor Fekete Nagyivány, 1. októbra 1870 – 4. novembra 1890",
          "Drahý otec! Nech je navždy Božie požehnanie pre vaše ušľachtilé snaženie a prácu, ktorú ste už 25 rokov na našej krásnej, no tŕnistej ceste vykonávali. Želám si, aby prozreteľnosť bola aj naďalej v zdraví a sile, na slávu vlasti a na šťastie našej rodiny. V Spišskej Novej Vsi, 14. októbra 1890, Tvoj  úprimne milujúci syn Károly",
          "",
          "",
          "Bojoval so cťou, v práci zošedivel. Jeho odmenou je verejná úcta. Nech sú vaše dni radostné a pokojné. Jovich/Joviek, 1890",
          "Nech je Tvoja neúnavná pracovitosť ozdobená vavrínovým vencom, lebo ty, môj milý dobrý otec, si zaslúžiš najväčšiu slávu. Milujúci syn Lajos, 4. novembra 1890",
          "",
          "Kto zasvätí svoj život všetkému peknému a ušľachtilému vo svojej práci a dosiahne to – môže sa za svojím životom obzerať spokojne. S pozdravom Gusztáv Matz, Debrecín",
          "",
          "",
          "",
          "",
          "",
          "",
          "Gustav Graeser †",
          "Jeho pohnutá minulosť je korunovaná jeho slávnou a slávnou prítomnosťou. Prajem mu, aby jeho budúcnosť bola spokojná a tým aj šťastná. Jeho vďačný, milujúci učeník Béla Zitkovszky, 1. októbra 1890",
          "Na vďačnú pamiatku môjho Majstra. \nEdmund Uher",
          "Svet korunuje vodcovo čelo len vavrínom; Boh dáva nebeskú korunu všetkým svojim bojovníkom. V Prešove v novembri 1890, vďačne milujúci syn Adolf József Divald",
          "Vytrvať a namáhať sa na hrboľatej ceste práce, stojac na najnižšom stupienku vrcholu svojej slávy získanej za štvrťstoročie. Tu vyjadrujem svoje prianie: Nech vás obloha vedie vašou prácou, ešte vyššie, viac, ďalej, aby som v druhom bode, k ďalšiemu jubileu „majstra, mohol vysloviť ako teraz: zo srdca vám želám veľa šťastia. Zostávam Váš pri všetkej úcte, József Ferenczy, 4.novembra 1890",
        ],
        photosTitles: [
          "Pamätný album",
          "Pamätný album",
          "Titulný list pamätného albumu",
          "Károly Divald st.",
          "Imre Egey",
          "Skupinový portrét Károlya Divalda a jeho učňov a zamestnancov",
          "János Varga",
          "György Varga",
          "József Juhász",
          "Sándor Fekete Nagyiványi",
          "Károly Divald ml.",
          "Árpád Turzer",
          "Károly Mathea",
          "Joviek",
          "Lajos Divald",
          "Skupinový portrét zamestnancov svetlotlačiarne",
          "Gusztáv Matz",
          "Divaldove dcéry (zľava Borbála?, Emília?, Iren a Mária?)",
          "Alajos Klapok",
          "Lajos Farkas",
          "Emil Gertinger",
          "Béla Ajtai",
          "A. Brabez",
          "Gusztav Graeser",
          "Béla Zitkovszky",
          "Ödön (Edmund) Uher",
          "Adolf Divald",
          "József Ferenczy",
        ],
      },
      "3": {
        title:
          "Rimamuránsko Šalgótarjánska hutnícka akciová spoločnosť na Milenárnej výstave",
        author: "Károly Divald ml.",
        year: "1896",
        photosTitles: [
          "Rimamuránsko Šalgótarjánska hutnícka akciová spoločnosť na Milenárnej výstave",
          "Plán pavilónu",
          "Vstup do pavilónu",
          "Železiarske podniky",
          "Rimamuránske železiarske podniky",
          "Čiastkový pohľad na podnik na výrobu plechov v Borsonádasde",
          "Huta Likéri",
          "Banský podnik v Rákosi",
          "Správa lesov v Rimavskom Brezove",
          "Koľajnice, drôty, drevené náradie",
          "Plechy a drôty",
          "Telegrafné drôty v rámci produkcie podniku",
          "Drôty a železná ruda",
          "Drôty a nástroje",
          "„Roh“ a ukážka vstupu do bane",
          "„Roh“, stroje a nástroje",
          "Vlnitý plech a železná ruda",
          "Plechy a ozubené kolesá",
          "Poľnohospodárske zariadenie a časti strojov",
          "Stroj na valcovanie plechov",
          "Skúšky koľajníc a ich ohnutí",
          "Kolesá, prevody a súčasti strojov",
          "Ukážky rôznych druhov rúd",
          "Dobývanie rúd",
          "Štôlňa Lászlo Vashegyi",
          "Výrobky domáceho drevárskeho priemyslu a ťažba dreva",
          "Drevené náradie a nástroje",
        ],
      },
    },
  },
  en: {
    sng: "Slovak National Gallery",
    library: {
      "1": {
        title: "Bardejovské Kúpele in Pictures",
        author: "Kornél Chyzer – Károly Divald",
        year: "1886",
        photosTitles: [
          "Bardejovské Kúpele in Pictures",
          "View of Bardejovské Kúpele from the southeast",
          "Bardejovská Street",
          "Church Square",
          "Main spring with spa hall",
          "Main Street",
          "Main Street",
          "Pond and City Hotel",
          "Church Square with new spa house",
          "Hot spring with old spa house",
          "Sweet Spring",
          "Sulphur spring",
          '"Faith, Love, and Hope" memorial',
          "Shower",
          "Panská Street",
          "Dance hall",
          "View of Bardejov from Calvary",
          "Bardejov town hall and church",
          "Ruins of Zborov Castle",
        ],
      },
      "2": {
        title: "Commemorative Album",
        author: "Divald's Studio",
        year: "1890",
        photosDescriptions: [
          "",
          "",
          "On the occasion of the 25th anniversary of Károly Divald Sr's company and the jubilee 5,000th image. 4 November 1890. Your employees",
          "",
          "November 1890 in Debrecen. A disciple bows to his master and pays his full respects as he is fortunate enough to celebrate the 60th birthday of a life rich in merit. May the God of the Hungarians preserve him in good health and cheerful spirits for the benefit and protection of his country, family, and ancestors for many, many years. I am, and will remain, a believer with the utmost respect. Imre Egey",
          "",
          "János Varga. Zagreb, 20 October 1890",
          "György Varga. Zagreb, 20 October 1890",
          "Juhász József †",
          "The most beautiful reward a pupil can give to a good teacher is ʼa feeling of gratitudeʻ - an emotion that permeates my soul whenever I think of my life's journey. Sándor Fekete Nagyivány, 1 October 1870 - 4 November 1890",
          "Dear father! May God's blessings be forever upon your noble efforts and the work you have done for 25 years on our beautiful yet thorny path. I wish that providence may continue to be in health and strength, for the glory of our country and the happiness of our family. In Spišská Nová Ves, 14 October 1890, Your sincerely loving son Károly",
          "",
          "",
          "He fought with honour, he grew grey at work. His reward is public respect. May your days be joyful and peaceful. Jovich/Joviek, 1890",
          "May your tireless diligence be adorned with a laurel wreath, for you, my dear good father, deserve the greatest glory. Loving son Lajos, 4 November 1890",
          "",
          "He who dedicates his life to all that is beautiful and noble in his work and achieves it - can look back on his life with satisfaction. Yours sincerely, Gusztáv Matz, Debrecen",
          "",
          "",
          "",
          "",
          "",
          "",
          "Gustav Graeser †",
          "His troubled past is crowned by his glorious present. I wish his future to be content and thus happy. His grateful, loving disciple Béla Zitkovszky, 1 October 1890",
          "In grateful commemoration of my Master. \nEdmund Uher",
          "The world crowns the leader's brow only with laurel; God gives the heavenly crown to all His warriors. In Prešov, November 1890, gratefully loving son Adolf József Divald",
          "To persevere and to toil on the bumpy road of labour, standing on the lowest step of the pinnacle of his quarter-century of earned glory. Here, I express my wish: may the sky guide you through your work, still higher, more, further, so that at the second point, on the next jubilee of the 'master', I may pronounce as I do now: from the bottom of my heart, I wish you good luck. I remain yours with all respect, József Ferenczy, 4 November 1890.",
        ],
        photosTitles: [
          "Commemorative Album",
          "Commemorative Album",
          "Commemorative Album title page",
          "Károly Divald Sr.",
          "Imre Egey",
          "Group portrait of Károly Divald and his apprentices and employees",
          "János Varga",
          "György Varga",
          "József Juhász",
          "Sándor Fekete Nagyiványi",
          "Károly Divald Jr.",
          "Árpád Turzer",
          "Károly Mathea",
          "Jovick",
          "Lajos Divald",
          "Group portrait of employees of the Collotype Printing House",
          "Gusztáv Matz",
          "Divald's daughters (from the left: Borbála?, Emilia?, Iren, and Maria?)",
          "Alajos Klapok",
          "Lajos Farkas",
          "Emil Gertinger",
          "Béla Ajtai",
          "A. Brabez",
          "Gusztav Graeser",
          "Béla Zitkovszky",
          "Ödön (Edmund) Uher",
          "Adolf Divald",
          "József Ferenczy",
        ],
      },
      "3": {
        title:
          "Rimamurány-Salgotarjan metallurgical joint-stock company at the Millennium Exhibition",
        author: "Károly Divald Jr",
        year: "1896",
        photosTitles: [
          "Rimamurány-Salgotarjan metallurgical joint-stock company at the Millennium Exhibition",
          "Pavilion plan",
          "Pavilion entrance",
          "Metallurgical plants",
          "Rimamurány metallurgical plants",
          "Partial view of the Borsodnádasd sheet metal plant",
          "Smeltery Likéri",
          "Mining plant in Rákos",
          "Forest administration in Rimavské Brezovo",
          "Rails, wires, wooden tools",
          "Sheets and wires",
          "Telegraph wires in the company's production",
          "Wires and iron ore",
          "Wires and tools",
          '"Corner" and view of the mine entrance',
          '"Corner", machines and tools',
          "Corrugated sheet and iron ore",
          "Sheets and gears",
          "Agricultural equipment and machinery parts",
          "Sheet metal rolling machine",
          "Tests of rails and their pliability",
          "Wheels, gears, and machine parts",
          "Samples of various types of ore",
          "Ore mining",
          "Drift László Vashegyi",
          "Products of the domestic timber industry and logging",
          "Wooden tools and instruments",
        ],
      },
    },
  },
};

export const LIBRARY: Array<Publication> = [
  {
    id: "1",
    pages: 19,
  },
  {
    id: "2",
    pages: 29,
  },
  {
    id: "3",
    pages: 26,
  },
];
